### ISSUE TITLE
No Module _thread

### ISSUE THREAD

**Issue by kalpitakolkar69** [ckoever/micropython-firebase-realtime-database#1]
>>> import ufirebase
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "ufirebase.py", line 4, in <module>
    ImportError: no module named '_thread'

**Comment by ckoever** [comment]
Which version of Micropython are you using?
Which microcontroller do you use?

Try to run help("modules"). If "_thread" is not listed, your micropython version does not support this firebase module. In this case you can delete the line in "ufirebase.py" with "import _thread" **and** **always** have to add "bg = False" to the functions.

_Example:_
`firebase.delete("count", bg=False)`
