### ISSUE TITLE
ENOMEM, try to restart. Do not make to many id's (sokets) simultaneously! (or use a board with more ram

### ISSUE THREAD

**Issue by b-madhukar** [ckoever/micropython-firebase-realtime-database#4]
Hello , I am trying your code on Wokwi ESP32 Micopython simulator .
while executing facing issue  "Do not make to many sockets".
Can you please check it once .

**Comment by b-madhukar** [comment]
![Error](https://user-images.githubusercontent.com/21213986/151305411-829e5fdf-2c46-4be8-8141-4d6e4857a476.JPG)

**Comment by ckoever** [comment]
I was able to reproduce this error on the wokwi simulator.
The main reason for this error message should actually be the low RAM.

![image](https://user-images.githubusercontent.com/77546092/151315646-cb8cee67-e203-4367-ab33-ace68c1a411b.png)

Normally this board should have <520KB RAM.
Instead it has "only" 120KB

![image](https://user-images.githubusercontent.com/77546092/151316009-3ed2bd76-35ac-4ffd-ac67-9e2dcd10ef12.png)

If i find the time, i will try to program a version for boards with less ram. But currently I'm working on version 2 (Beta)

**Comment by b-madhukar** [comment]
Thanks for the fast reply @ckoever 
May i know why it is showing as too many sockets.
Can't we change the code to not produce more number of sockets

**Comment by ckoever** [comment]
_Normally_ this error occures **only** if the functions runs in background (with bg=1, in documentation) where you **can** but not have to generate more then 1 socket.
```
firebase.put(..., bg=1, id=0)
firebase.put(..2, bg=1, id=1)
firebase.get(..., bg=1, id=0)
```
![image](https://user-images.githubusercontent.com/77546092/151324078-cf4003e2-bfa5-4835-a210-7cb1153be460.png)

If this code is running with bg=0 and id=x(0)
![image](https://user-images.githubusercontent.com/77546092/151324718-3f2f93ed-5166-4159-a2fa-f5f8177928a4.png)

This is the reason why sometimes the RAM of some Micropython Boars is not enough.

But i change the error text to "if you use more sockets simultaneously..."
